#pragma once


#ifdef STM32F446_NUCLEO


// CAN1
#define CN9_CAN1_RX_PORT	GPIOD
#define CN9_CAN1_RX_PIN		GPIO_PIN_0
#define CN9_CAN1_RX_AF		GPIO_AF9_CAN1

#define CN9_CAN1_TX_PORT	GPIOD
#define CN9_CAN1_TX_PIN		GPIO_PIN_1
#define CN9_CAN1_TX_AF		GPIO_AF9_CAN1

// CAN2
#define CN12_CAN2_RX_PORT	GPIOB
#define CN12_CAN2_RX_PIN	GPIO_PIN_5
#define CN12_CAN2_RX_AF		GPIO_AF9_CAN2

#define CN12_CAN2_TX_PORT	GPIOB
#define CN12_CAN2_TX_PIN	GPIO_PIN_6
#define CN12_CAN2_TX_AF		GPIO_AF9_CAN2


#endif
